export const CAKES = [
  {
    id: 0,
    name: "Seaside Clam Cake",
    price: "$33.50",
    category: "Custom Cake",
    visible: true,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!",
    image: "/assets/images/clamshell.png",
    thumbnail: "/assets/images/chrome-river.jpg",
    ratings: "3",
  },
  {
    id: 1,
    name: "Dynosaur Train Cake",
    price: "$24.99",
    category: "Birthday Cake",
    visible: true,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!",
    image: "/assets/images/jibbs-item.png",
    thumbnail: "/assets/images/jibbs-item.png",
    ratings: "4",
  },
  {
    id: 2,
    name: "Fresh Fruit Cake",
    price: "$40.20",
    category: "Birthday Cake",
    visible: true,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!",
    image: "/assets/images/fruit.png",
    thumbnail: "/assets/images/chrome-river.jpg",
    ratings: "3",
  },
  {
    id: 3,
    name: "Frozen Theme Cake",
    price: "$54.20",
    category: "Birthday Cake",
    visible: true,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!",
    image: "/assets/images/frozen.png",
    thumbnail: "/assets/images/chrome-river.jpg",
    ratings: "4",
  },
    {
    id: 4,
    name: "Wedding Cake",
    price: "$300.20",
    category: "Wedding Cake",
    visible: true,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!",
    image: "/assets/images/wedding-cake.png",
    thumbnail: "/assets/images/chrome-river.jpg",
    ratings: "5",
  },
      {
    id: 5,
    name: "Voodoo Donuts",
    price: "$300.20",
    category: "Cup Cake",
    visible: true,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!",
    image: "/assets/images/kelly-item.png",
    thumbnail: "/assets/images/chrome-river.jpg",
    ratings: "4",
  },
        {
    id: 7,
    name: "Cup cakes",
    price: "$30.10",
    category: "Cup Cake",
    visible: true,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!",
    image: "/assets/images/deva-item.png",
    thumbnail: "/assets/images/chrome-river.jpg",
    ratings: "3",
  },
        {
    id: 8,
    name: "Butter Cream Cake",
    price: "$60.00",
    category: "Custom Cake",
    visible: true,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!",
    image: "/assets/images/logan-item.png",
    thumbnail: "/assets/images/chrome-river.jpg",
    ratings: "4",
  },
          {
    id: 9,
    name: "Moustache Cake",
    price: "$60.00",
    category: "Custom Cake",
    visible: true,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!",
    image: "/assets/images/moustache.png",
    thumbnail: "/assets/images/chrome-river.jpg",
    ratings: "5",
  },
];
